/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Track } from "./Track";
import { TrackCountArgs } from "./TrackCountArgs";
import { TrackFindManyArgs } from "./TrackFindManyArgs";
import { TrackFindUniqueArgs } from "./TrackFindUniqueArgs";
import { CreateTrackArgs } from "./CreateTrackArgs";
import { UpdateTrackArgs } from "./UpdateTrackArgs";
import { DeleteTrackArgs } from "./DeleteTrackArgs";
import { Playlist } from "../../playlist/base/Playlist";
import { TrackService } from "../track.service";
@graphql.Resolver(() => Track)
export class TrackResolverBase {
  constructor(protected readonly service: TrackService) {}

  async _tracksMeta(
    @graphql.Args() args: TrackCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Track])
  async tracks(@graphql.Args() args: TrackFindManyArgs): Promise<Track[]> {
    return this.service.tracks(args);
  }

  @graphql.Query(() => Track, { nullable: true })
  async track(
    @graphql.Args() args: TrackFindUniqueArgs
  ): Promise<Track | null> {
    const result = await this.service.track(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Track)
  async createTrack(@graphql.Args() args: CreateTrackArgs): Promise<Track> {
    return await this.service.createTrack({
      ...args,
      data: {
        ...args.data,

        playlist: args.data.playlist
          ? {
              connect: args.data.playlist,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Track)
  async updateTrack(
    @graphql.Args() args: UpdateTrackArgs
  ): Promise<Track | null> {
    try {
      return await this.service.updateTrack({
        ...args,
        data: {
          ...args.data,

          playlist: args.data.playlist
            ? {
                connect: args.data.playlist,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Track)
  async deleteTrack(
    @graphql.Args() args: DeleteTrackArgs
  ): Promise<Track | null> {
    try {
      return await this.service.deleteTrack(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Playlist, {
    nullable: true,
    name: "playlist",
  })
  async getPlaylist(@graphql.Parent() parent: Track): Promise<Playlist | null> {
    const result = await this.service.getPlaylist(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
