/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Playlist } from "./Playlist";
import { PlaylistCountArgs } from "./PlaylistCountArgs";
import { PlaylistFindManyArgs } from "./PlaylistFindManyArgs";
import { PlaylistFindUniqueArgs } from "./PlaylistFindUniqueArgs";
import { CreatePlaylistArgs } from "./CreatePlaylistArgs";
import { UpdatePlaylistArgs } from "./UpdatePlaylistArgs";
import { DeletePlaylistArgs } from "./DeletePlaylistArgs";
import { TrackFindManyArgs } from "../../track/base/TrackFindManyArgs";
import { Track } from "../../track/base/Track";
import { PlaylistService } from "../playlist.service";
@graphql.Resolver(() => Playlist)
export class PlaylistResolverBase {
  constructor(protected readonly service: PlaylistService) {}

  async _playlistsMeta(
    @graphql.Args() args: PlaylistCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Playlist])
  async playlists(
    @graphql.Args() args: PlaylistFindManyArgs
  ): Promise<Playlist[]> {
    return this.service.playlists(args);
  }

  @graphql.Query(() => Playlist, { nullable: true })
  async playlist(
    @graphql.Args() args: PlaylistFindUniqueArgs
  ): Promise<Playlist | null> {
    const result = await this.service.playlist(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Playlist)
  async createPlaylist(
    @graphql.Args() args: CreatePlaylistArgs
  ): Promise<Playlist> {
    return await this.service.createPlaylist({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Playlist)
  async updatePlaylist(
    @graphql.Args() args: UpdatePlaylistArgs
  ): Promise<Playlist | null> {
    try {
      return await this.service.updatePlaylist({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Playlist)
  async deletePlaylist(
    @graphql.Args() args: DeletePlaylistArgs
  ): Promise<Playlist | null> {
    try {
      return await this.service.deletePlaylist(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Track], { name: "tracks" })
  async findTracks(
    @graphql.Parent() parent: Playlist,
    @graphql.Args() args: TrackFindManyArgs
  ): Promise<Track[]> {
    const results = await this.service.findTracks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
