/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Ad } from "./Ad";
import { AdCountArgs } from "./AdCountArgs";
import { AdFindManyArgs } from "./AdFindManyArgs";
import { AdFindUniqueArgs } from "./AdFindUniqueArgs";
import { CreateAdArgs } from "./CreateAdArgs";
import { UpdateAdArgs } from "./UpdateAdArgs";
import { DeleteAdArgs } from "./DeleteAdArgs";
import { AdService } from "../ad.service";
@graphql.Resolver(() => Ad)
export class AdResolverBase {
  constructor(protected readonly service: AdService) {}

  async _adsMeta(@graphql.Args() args: AdCountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Ad])
  async ads(@graphql.Args() args: AdFindManyArgs): Promise<Ad[]> {
    return this.service.ads(args);
  }

  @graphql.Query(() => Ad, { nullable: true })
  async ad(@graphql.Args() args: AdFindUniqueArgs): Promise<Ad | null> {
    const result = await this.service.ad(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Ad)
  async createAd(@graphql.Args() args: CreateAdArgs): Promise<Ad> {
    return await this.service.createAd({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Ad)
  async updateAd(@graphql.Args() args: UpdateAdArgs): Promise<Ad | null> {
    try {
      return await this.service.updateAd({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Ad)
  async deleteAd(@graphql.Args() args: DeleteAdArgs): Promise<Ad | null> {
    try {
      return await this.service.deleteAd(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
